# Use root/example as user/password credentials

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
#    command:
#      - --ssl-ca=/var/lib/mysql-certs/ca.pem
#      - --ssl-cert=/var/lib/mysql-certs/server-cert.pem
#      - --ssl-key=/var/lib/mysql-certs/server-key.pem
#      - --require-secure-transport=ON
    ports:
      - 3306:3306
    volumes:
      - ./mysql-certs:/var/lib/mysql-certs
