name: CLI E2EE Tests

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25.2"
      - name: Install dependencies
        run: go get .
      - name: Build the CLI
        run: go build -o infisical-cli
      - name: Checkout infisical repo
        uses: actions/checkout@v6
        with:
          repository: infisical/infisical
          path: infisical
      - name: Test with the Go CLI
        run: go test -v -timeout 30m -count=1 github.com/infisical/cli/e2e-tests/...
        working-directory: ./e2e
        env:
          INFISICAL_BACKEND_DIR: ${{ github.workspace }}/infisical/backend
          INFISICAL_CLI_EXECUTABLE: ${{ github.workspace }}/infisical-cli
          CLI_E2E_DEFAULT_RUN_METHOD: subprocess